### ISSUE TITLE
2.26.1-lin-arm64 fails to open the module browser when installed. Crash/lockup.

### ISSUE THREAD

**Issue by jackokring** [clone45/voxglitch#217]
Deleting the plugin restores browser functionality.

**Comment by jackokring** [comment]
2.25.1 also stalls on loading the right click add module browser. Maybe it's the large size, 14 MB, but the symptom goes away when the module is removed.

**Comment by clone45** [comment]
Hello!  This might take me a little while to troubleshoot.  It's unlikely to be the file size, since that's been consistent for quite a few versions.  Could you send me the VCV Rack log file that's generated after one of these crashes?

**Comment by jackokring** [comment]
I haven't got one. I checked out 2.21.2 and it doesn't have the problem.

**Comment by clone45** [comment]
OK, I'll see what I can do by comparing those two versions.  I'll keep you posted!

**Comment by cbix** [comment]
I'm also experiencing a crash for self-compiled Rack + voxglitch. For some reason the statically linked stdlibc++ doesn't include debug symbols but the rest does, so I could do some debugging:
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140735320269456}}
        ret = <optimized out>
#1  0x000079e44dca56d3 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:89
No locals.
#2  0x000079e44dc4bba0 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#3  0x000079e44dc33582 in __GI_abort () at abort.c:73
        act = {__sigaction_handler = {sa_handler = 0x46a, sa_sigaction = 0x46a}, sa_mask = {__val = {
              134021242262392, 134021465991968, 9648, 140735320269616, 1580, 134021465991872, 18446744073709551520, 
              140735320269952, 105228865573808, 140735320269664, 134021464670879, 140735320269648, 134021241493074, 
              105228870478096, 1580, 105228870418576}}, sa_flags = 2126881936, sa_restorer = 0x7fff7ec5a380}
#4  0x000079e44e0917f0 in std::__glibcxx_assert_fail(char const*, int, char const*, char const*) ()
   from /usr/lib/libRack.so
No symbol table info available.
#5  0x000079e4407f32dd in std::vector<float, std::allocator<float> >::operator[] (this=0x5fb48171ef10, 
    __n=<optimized out>) at /usr/include/c++/14.2.1/bits/stl_vector.h:992
        __PRETTY_FUNCTION__ = <optimized out>
#6  WaveformWidget::WaveformWidget (this=0x5fb48171ee20, width=399, height=45.9029999, 
    waveform_model=<optimized out>) at src/vgLib-2.0/widgets/WaveformWidget.hpp:55
        i = <optimized out>
#7  AutobreakStudioWidget::AutobreakStudioWidget (this=<optimized out>, module=<optimized out>, 
    this=<optimized out>, module=<optimized out>) at src/AutobreakStudio/AutobreakStudioWidget.hpp:92
```

Looking at the relevant code:

https://github.com/clone45/voxglitch/blob/3e3621e78b376193ef376ebc653301f6197ff110/src/vgLib-2.0/widgets/WaveformWidget.hpp#L51-L56

this looks a bit dangerous for 2 reasons:
1. only doing `reserve`, not `resize`, and then possibly assigning out of bounds
2. float → unsigned int conversion (possible loss of precision?)

Changing `reserve` → `resize` fixes the crash for Autobreak Studio, didn't test all the other modules yet.

**Comment by clone45** [comment]
Hi @cbix (Florian!) -- Thank so much for doing the extra work to find the issue here.  I'll try to get this fixed within a few days.  :-)

**Comment by cbix** [comment]
@clone45 great, you're welcome :) Another tiny request, it would be nice to have proper git tags for releases again, they stop at some point: https://github.com/clone45/voxglitch/releases
