### ISSUE TITLE
Autobreak seg fault with patterns -V

### ISSUE THREAD

**Issue by Coirt** [clone45/voxglitch#7]
sending negative voltage to autobreak pattern select mod port causes a segmentation fault. A guess: Likely index out of bounds. 

```
Thread 21 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 14204.0x3634]
0x00000000202de4b9 in Autobreak::process (this=0x2e528c90, args=...)
    at src/autobreak.cpp:278
278                                     float new_step = break_patterns[selected_break_pattern][break_pattern_index];
(gdb) bt
#0  0x00000000202de4b9 in Autobreak::process (this=0x2e528c90, args=...)
    at src/autobreak.cpp:278
#1  0x000000000049e3a7 in rack::engine::Engine_stepModules (threadId=0,
    that=<optimized out>) at src/engine/Engine.cpp:269
#2  0x00000000004a08a5 in rack::engine::Engine_step (that=<optimized out>)
    at src/engine/Engine.cpp:346
#3  rack::engine::Engine_run (that=<optimized out>)
    at src/engine/Engine.cpp:448
#4  rack::engine::Engine::<lambda()>::operator() (__closure=<optimized out>)
    at src/engine/Engine.cpp:482
#5  std::__invoke_impl<void, rack::engine::Engine::start()::<lambda()> > (
    __f=...) at C:/msys64/mingw64/include/c++/9.2.0/bits/invoke.h:60
#6  std::__invoke<rack::engine::Engine::start()::<lambda()> > (__fn=...)
    at C:/msys64/mingw64/include/c++/9.2.0/bits/invoke.h:95
#7  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::_M_invoke<0> (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/9.2.0/thread:244
#8  std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > >::operator() (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/9.2.0/thread:251
#9  std::thread::_State_impl<std::thread::_Invoker<std::tuple<rack::engine::Engine::start()::<lambda()> > > >::_M_run(void) (this=<optimized out>)
    at C:/msys64/mingw64/include/c++/9.2.0/thread:195
#10 0x000000006fd42441 in ?? () from C:\msys64\mingw64\bin\libstdc++-6.dll
#11 0x0000000064945092 in pthread_create_wrapper ()
   from C:\msys64\mingw64\bin\libwinpthread-1.dll
#12 0x00007ff8228ab04a in msvcrt!_beginthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#13 0x00007ff8228ab11c in msvcrt!_endthreadex ()
   from C:\WINDOWS\System32\msvcrt.dll
#14 0x00007ff822e77bd4 in KERNEL32!BaseThreadInitThunk ()
   from C:\WINDOWS\System32\kernel32.dll
#15 0x00007ff824daced1 in ntdll!RtlUserThreadStart ()
   from C:\WINDOWS\SYSTEM32\ntdll.dll
#16 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)

```

**Comment by clone45** [comment]
This has been fixed in the newest build.  I didn't realize that a negative float value would cause trouble when casting to an unsigned int.  Lesson learned!

**Comment by Coirt** [comment]
> This has been fixed in the newest build. I didn't realize that a negative float value would cause trouble when casting to an unsigned int. Lesson learned!

You and me both 😄
